User doesn't have to pick SGX core revision
Startup script now manages symlink to select correct chip
revision automatically

diff --git a/data/powervr.in b/data/powervr.in
--- a/data/powervr.in
+++ b/data/powervr.in
@@ -1,6 +1,7 @@
 #!/bin/sh
 set -e
 ARCH=$(uname -m)
+
 if [ "${ARCH#arm}" != "${ARCH}" ] ; then
   # Fix kernel oops by locking CPU frequency
   # https://github.com/maemo-leste/bugtracker/issues/212
@@ -9,10 +10,30 @@ if [ "${ARCH#arm}" != "${ARCH}" ] ; then
   modprobe pvrsrvkm
   echo $GOVERNOR > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
 
-  @prefix@/sbin/pvrsrvinit
+  SGX_CORE_REV=$(grep -Eo "SGX revision = [0-9]\.[0-9]\.[0-9]" \
+                 /proc/pvr/version | cut -d= -f 2 | tr -d ". ")
+
+  if [ "$SGX_CORE_REV" = "" ]; then
+    echo "Unable to determine SGX core revision" >&2
+    exit 1
+  fi
+
+  if [ ! -d "@pkglibexecdir@/r$SGX_CORE_REV" ]; then
+    echo "Unsupported SGX core revision" >&2
+    exit 1
+  fi
+
+  # Activate correct SGX libraries based on the chip revision
+  SELECTED_REV=$(readlink @pkglibexecdir@/current)
+  if [ "r$SGX_CORE_REV" != "$SELECTED_REV" ]; then
+    ln -snf r$SGX_CORE_REV @pkglibexecdir@/current
+  fi
+
+  @pkglibexecdir@/current/pvrsrvinit
   modprobe omaplfb
   chgrp video /dev/pvrsrvkm
   chmod 660 /dev/pvrsrvkm
 fi
+
 [ -x /bin/systemd-notify ] && exec /bin/systemd-notify --ready
 exit 0
